vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       productImages:
           uri_prefix: /images/products
           upload_destination: '%app.product_image_location%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
